<div align="center">

# **<span style="color:#38BDF8">Day 4 Summary — Pandas</span>**


#### This notebook summarizes everything about Pandas DataFrames, explained step by step with examples.
</div>

**____________________________________________________________________________________________________________________________________________________________________________**

## **<span style="color:#38BDF8">0. What Is Pandas?**</span>
#### Pandas is the main Python library for working with tabular (spreadsheet-like) data — think of it as Excel, but inside Python and much more powerful.

**<span style="color:#FACC15">Its two core objects:**</span>  
**<span style="color:#FACC15">- Series : a single labeled column of data**</span>  
**<span style="color:#FACC15">- DataFrame : a full table — rows and named columns, exactly like a CSV, Excel sheet, or SQL query result**</span>

In [1]:
# Always start by importing pandas with the alias 'pd'
import pandas as pd
import numpy as np

## **<span style="color:#38BDF8">1. Series vs. DataFrame**</span>
#### A Series is one column with labels (called an index). A DataFrame is a collection of Series sharing the same index — basically a table.

In [2]:
# A Series: one column of data with an index
ages = pd.Series([21, 25, 19, 30], name="age")
print(ages)
print(type(ages))

0    21
1    25
2    19
3    30
Name: age, dtype: int64
<class 'pandas.Series'>

In [3]:
# A DataFrame: a full table made of several columns (Series)
students = pd.DataFrame({
    "name": ["Sara", "Omar", "Layla", "Ahmad"],
    "age": [21, 25, 19, 30],
    "city": ["Nablus", "Ramallah", "Jenin", "Hebron"]
})
print(students)
print(type(students))

    name  age      city
0   Sara   21    Nablus
1   Omar   25  Ramallah
2  Layla   19     Jenin
3  Ahmad   30    Hebron
<class 'pandas.DataFrame'>

## **<span style="color:#38BDF8">2. Loading and Inspecting Data**</span>
#### The first step with any dataset is always to load it, then look at it before doing anything else: its shape, its columns, its data types, and a sample of rows.

**<span style="color:#BE185D">Key functions:**</span>  
**<span style="color:#BE185D">- pd.read_csv("file.csv") : loads a CSV file into a DataFrame**</span>  
**<span style="color:#BE185D">- .head() : shows the first 5 rows**</span>  
**<span style="color:#BE185D">- .shape : returns (rows, columns)**</span>  
**<span style="color:#BE185D">- .info() : shows column names, non-null counts, and data types**</span>  
**<span style="color:#BE185D">- .describe() : shows summary statistics for numeric columns**</span>

In [4]:
# We'll simulate a real dataset here instead of reading a CSV file,
# so this notebook runs on its own without needing an external file.
# In real life you would write: df = pd.read_csv("data.csv")

np.random.seed(42)  # fixes randomness so results are repeatable

df = pd.DataFrame({
    "name": ["Sara", "Omar", "Layla", "Ahmad", "Nour", "Khaled", "Rana", "Yousef"],
    "age": [21, 25, 19, np.nan, 30, 22, 28, 24],
    "city": ["Nablus", "Ramallah", "Jenin", "Hebron", "Nablus", "Ramallah", "Jenin", "Nablus"],
    "income": [1200, 1800, 900, 1500, 2000, 1100, np.nan, 1700]
})

df.head()  # first 5 rows

    name   age      city  income
0   Sara  21.0    Nablus  1200.0
1   Omar  25.0  Ramallah  1800.0
2  Layla  19.0     Jenin   900.0
3  Ahmad   NaN    Hebron  1500.0
4   Nour  30.0    Nablus  2000.0

In [5]:
print("Shape (rows, columns):", df.shape)
print("------------------------------")
df.info()   # column names, non-null counts, dtypes

Shape (rows, columns): (8, 4)
------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    8 non-null      str
 1   age     7 non-null      float64
 2   city    8 non-null      str
 3   income  7 non-null      float64
dtypes: float64(2), str(2)
memory usage: 388.0 bytes

In [6]:
df.describe()   # summary statistics for numeric columns only

             age       income
count   7.000000     7.000000
mean   24.142857  1457.142857
std     3.891382   403.555625
min    19.000000   900.000000
25%    21.500000  1150.000000
50%    24.000000  1500.000000
75%    26.500000  1750.000000
max    30.000000  2000.000000

## **<span style="color:#38BDF8">3. Selecting and Filtering**</span>
#### You can select columns by name, and select rows by a condition (this is called boolean filtering — the Pandas equivalent of NumPy's boolean masking).

**<span style="color:#FACC15">- .loc[ ] selects by label (column/row name)**</span>  
**<span style="color:#FACC15">- .iloc[ ] selects by integer position**</span>

In [7]:
# Selecting a single column returns a Series
print(df["age"])

0    21.0
1    25.0
2    19.0
3     NaN
4    30.0
5    22.0
6    28.0
7    24.0
Name: age, dtype: float64

In [8]:
# Selecting multiple columns returns a DataFrame (note the double brackets)
df[["name", "income"]]

     name  income
0    Sara  1200.0
1    Omar  1800.0
2   Layla   900.0
3   Ahmad  1500.0
4    Nour  2000.0
5  Khaled  1100.0
6    Rana     NaN
7  Yousef  1700.0

In [9]:
# Filtering rows where age is greater than 22
df[df["age"] > 22]

     name   age      city  income
1    Omar  25.0  Ramallah  1800.0
4    Nour  30.0    Nablus  2000.0
6    Rana  28.0     Jenin     NaN
7  Yousef  24.0    Nablus  1700.0

In [10]:
# .loc : select the income column, but only for rows where age > 22
df.loc[df["age"] > 22, "income"]

1    1800.0
4    2000.0
6       NaN
7    1700.0
Name: income, dtype: float64

## **<span style="color:#38BDF8">4. Cleaning Data**</span>
#### Real data is messy: missing values, duplicates, and wrong types are the norm. Cleaning is often the largest part of any data project, and doing it correctly is what everything downstream depends on.

**<span style="color:#BE185D">- .isnull().sum() : counts missing values per column**</span>  
**<span style="color:#BE185D">- .fillna(value) : fills missing values with something (e.g. the mean)**</span>  
**<span style="color:#BE185D">- .dropna() : removes rows that contain missing values**</span>  
**<span style="color:#BE185D">- .drop_duplicates() : removes duplicate rows**</span>

In [11]:
# Step 1: Count missing values per column
df.isnull().sum()

name      0
age       1
city      0
income    1
dtype: int64

In [12]:
# Step 2: Fill missing 'age' values with the average age
df["age"] = df["age"].fillna(df["age"].mean())

# Step 3: Fill missing 'income' values with the average income
df["income"] = df["income"].fillna(df["income"].mean())

print("Missing values after cleaning:")
df.isnull().sum()

Missing values after cleaning:

name      0
age       0
city      0
income    0
dtype: int64

In [13]:
# Removing duplicate rows (none exist here, but this is how you would do it)
df = df.drop_duplicates()
df

     name        age      city       income
0    Sara  21.000000    Nablus  1200.000000
1    Omar  25.000000  Ramallah  1800.000000
2   Layla  19.000000     Jenin   900.000000
3   Ahmad  24.142857    Hebron  1500.000000
4    Nour  30.000000    Nablus  2000.000000
5  Khaled  22.000000  Ramallah  1100.000000
6    Rana  28.000000     Jenin  1457.142857
7  Yousef  24.000000    Nablus  1700.000000

**<span style="color:#4ADE80">Note: We filled the missing values instead of dropping them (df.dropna()), because dropping rows means losing real data. Filling with the mean is a common, simple strategy for numeric columns.</span>**

## **<span style="color:#38BDF8">5. Grouping and Aggregation (groupby)**</span>
#### groupby splits the data into groups based on a column's values, applies an aggregation (mean, sum, count...) to each group, then combines the results. This is the single most useful Pandas operation for finding patterns in data — known as **"split → apply → combine"**.

In [14]:
# Average income per city
df.groupby("city")["income"].mean()

city
Hebron      1500.000000
Jenin       1178.571429
Nablus      1633.333333
Ramallah    1450.000000
Name: income, dtype: float64

In [15]:
# Multiple aggregations at once: average income AND maximum age, per city
df.groupby("city").agg({"income": "mean", "age": "max"})

               income        age
city
Hebron    1500.000000  24.142857
Jenin     1178.571429  28.000000
Nablus    1633.333333  30.000000
Ramallah  1450.000000  25.000000

## **<span style="color:#38BDF8">6. Mini Project — Putting It All Together**</span>
#### A small, professional example that follows the same load → inspect → clean → filter → group pipeline used with any real dataset.

In [16]:
# Step 1: Report shape, columns, and dtypes
print("Shape:", df.shape)
print("Columns:", list(df.columns))
print("Dtypes:\n", df.dtypes)

Shape: (8, 4)
Columns: ['name', 'age', 'city', 'income']
Dtypes:
 name          str
age       float64
city          str
income    float64
dtype: object

In [17]:
# Step 2: Filter to a meaningful subset — people earning above the average income
average_income = df["income"].mean()
high_earners = df[df["income"] > average_income]
print(f"Average income: {average_income:.2f}")
high_earners

Average income: 1457.14

     name        age      city  income
1    Omar  25.000000  Ramallah  1800.0
3   Ahmad  24.142857    Hebron  1500.0
4    Nour  30.000000    Nablus  2000.0
7  Yousef  24.000000    Nablus  1700.0

In [18]:
# Step 3: Aggregate statistic per category, interpreted below
city_summary = df.groupby("city").agg({"income": "mean", "age": "mean"})
city_summary

               income        age
city
Hebron    1500.000000  24.142857
Jenin     1178.571429  23.500000
Nablus    1633.333333  25.000000
Ramallah  1450.000000  23.500000

**<span style="color:#FACC15">Interpretation: Nablus has the highest average income among the three cities in this sample, while Jenin has the lowest. This kind of grouped summary is exactly what groupby is used for — spotting patterns across categories at a glance.</span>**

## **<span style="color:#38BDF8">7. Quick Summary**</span>

**<span style="color:#FACC15">- Series = one labeled column, DataFrame = a full table of Series**</span>  
**<span style="color:#FACC15">- Always inspect data first with .head(), .shape, .info(), .describe()**</span>  
**<span style="color:#FACC15">- Select columns with df["col"], filter rows with df[df["col"] > x]**</span>  
**<span style="color:#FACC15">- .loc selects by label, .iloc selects by position**</span>  
**<span style="color:#FACC15">- Clean data with .isnull(), .fillna(), .dropna(), .drop_duplicates()**</span>  
**<span style="color:#FACC15">- groupby follows split → apply → combine to summarize data by category**</span>

<div align="center">